"""Initial migration

Revision ID: e9e024068025
Revises: 
Create Date: 2026-02-07 21:25:46.428941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e024068025'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.String(length=20000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_table('student_2')
    # op.drop_table('products')
    # op.drop_table('student')
    # op.drop_table('products_2')
    # op.drop_table('products_3')
    # op.drop_table('orders_3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_3',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products_3.id'], name=op.f('orders_3_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_3_pkey'))
    )
    op.create_table('products_3',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('products_3_pkey')),
    sa.UniqueConstraint('email', name=op.f('products_3_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('products_2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('products_2_pkey')),
    sa.UniqueConstraint('email', name=op.f('products_2_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('student',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID', name=op.f('student_pkey')),
    sa.UniqueConstraint('email', name=op.f('student_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey')),
    sa.UniqueConstraint('email', name=op.f('products_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('student_2',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID', name=op.f('student_2_pkey')),
    sa.UniqueConstraint('email', name=op.f('student_2_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('article')
    # ### end Alembic commands ###
